/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * RCL Staff Portal API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Get current authenticated user
 */
export const GetMeResponse = zod.object({
  discordId: zod.string(),
  username: zod.string(),
  discriminator: zod.string().nullish(),
  avatar: zod.string().nullable(),
  role: zod.enum([
    "owner",
    "hicom",
    "head_mod",
    "senior_mod",
    "moderator",
    "trial_mod",
    "pending",
    "none",
  ]),
  status: zod.enum(["approved", "pending", "declined", "blacklisted", "none"]),
  blacklistedUntil: zod.string().nullish(),
});

/**
 * @summary Log out
 */
export const LogoutResponse = zod.object({
  success: zod.boolean(),
});

/**
 * @summary List all pending applications (HICOM+ only)
 */
export const ListApplicationsResponseItem = zod.object({
  id: zod.number(),
  discordId: zod.string(),
  username: zod.string(),
  discriminator: zod.string().nullish(),
  avatar: zod.string().nullable(),
  status: zod.enum(["pending", "approved", "declined", "blacklisted"]),
  role: zod.string().nullish(),
  blacklistedUntil: zod.string().nullish(),
  reviewedBy: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string().nullish(),
});
export const ListApplicationsResponse = zod.array(ListApplicationsResponseItem);

/**
 * @summary Get the current user's own application status
 */
export const GetMyApplicationResponse = zod.object({
  id: zod.number(),
  discordId: zod.string(),
  username: zod.string(),
  discriminator: zod.string().nullish(),
  avatar: zod.string().nullable(),
  status: zod.enum(["pending", "approved", "declined", "blacklisted"]),
  role: zod.string().nullish(),
  blacklistedUntil: zod.string().nullish(),
  reviewedBy: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string().nullish(),
});

/**
 * @summary Approve an application and assign a role
 */
export const ApproveApplicationParams = zod.object({
  id: zod.coerce.number(),
});

export const ApproveApplicationBody = zod.object({
  role: zod.enum(["trial_mod", "moderator", "senior_mod", "head_mod", "hicom"]),
});

export const ApproveApplicationResponse = zod.object({
  id: zod.number(),
  discordId: zod.string(),
  username: zod.string(),
  discriminator: zod.string().nullish(),
  avatar: zod.string().nullable(),
  status: zod.enum(["pending", "approved", "declined", "blacklisted"]),
  role: zod.string().nullish(),
  blacklistedUntil: zod.string().nullish(),
  reviewedBy: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string().nullish(),
});

/**
 * @summary Decline an application
 */
export const DeclineApplicationParams = zod.object({
  id: zod.coerce.number(),
});

export const DeclineApplicationResponse = zod.object({
  id: zod.number(),
  discordId: zod.string(),
  username: zod.string(),
  discriminator: zod.string().nullish(),
  avatar: zod.string().nullable(),
  status: zod.enum(["pending", "approved", "declined", "blacklisted"]),
  role: zod.string().nullish(),
  blacklistedUntil: zod.string().nullish(),
  reviewedBy: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string().nullish(),
});

/**
 * @summary Blacklist a Discord user for 10 days
 */
export const BlacklistApplicantParams = zod.object({
  id: zod.coerce.number(),
});

export const BlacklistApplicantResponse = zod.object({
  id: zod.number(),
  discordId: zod.string(),
  username: zod.string(),
  discriminator: zod.string().nullish(),
  avatar: zod.string().nullable(),
  status: zod.enum(["pending", "approved", "declined", "blacklisted"]),
  role: zod.string().nullish(),
  blacklistedUntil: zod.string().nullish(),
  reviewedBy: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string().nullish(),
});

/**
 * @summary Get application statistics
 */
export const GetApplicationStatsResponse = zod.object({
  total: zod.number(),
  pending: zod.number(),
  approved: zod.number(),
  declined: zod.number(),
  blacklisted: zod.number(),
});

/**
 * @summary List all staff profiles
 */
export const ListStaffResponseItem = zod.object({
  id: zod.number(),
  discordId: zod.string(),
  username: zod.string(),
  avatar: zod.string().nullish(),
  timezone: zod.string().nullish(),
  about: zod.string().nullish(),
  role: zod.enum(["hicom", "head_mod", "senior_mod", "moderator", "trial_mod"]),
  createdAt: zod.string(),
  updatedAt: zod.string().nullish(),
});
export const ListStaffResponse = zod.array(ListStaffResponseItem);

/**
 * @summary Create a staff profile (HICOM+ only)
 */
export const CreateStaffProfileBody = zod.object({
  discordId: zod.string(),
  username: zod.string(),
  avatar: zod.string().nullish(),
  timezone: zod.string().nullish(),
  about: zod.string().nullish(),
  role: zod.enum(["hicom", "head_mod", "senior_mod", "moderator", "trial_mod"]),
});

/**
 * @summary Get a staff profile by ID
 */
export const GetStaffProfileParams = zod.object({
  id: zod.coerce.number(),
});

export const GetStaffProfileResponse = zod.object({
  id: zod.number(),
  discordId: zod.string(),
  username: zod.string(),
  avatar: zod.string().nullish(),
  timezone: zod.string().nullish(),
  about: zod.string().nullish(),
  role: zod.enum(["hicom", "head_mod", "senior_mod", "moderator", "trial_mod"]),
  createdAt: zod.string(),
  updatedAt: zod.string().nullish(),
});

/**
 * @summary Update a staff profile (HICOM+ only)
 */
export const UpdateStaffProfileParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateStaffProfileBody = zod.object({
  username: zod.string().optional(),
  avatar: zod.string().nullish(),
  timezone: zod.string().nullish(),
  about: zod.string().nullish(),
  role: zod
    .enum(["hicom", "head_mod", "senior_mod", "moderator", "trial_mod"])
    .optional(),
});

export const UpdateStaffProfileResponse = zod.object({
  id: zod.number(),
  discordId: zod.string(),
  username: zod.string(),
  avatar: zod.string().nullish(),
  timezone: zod.string().nullish(),
  about: zod.string().nullish(),
  role: zod.enum(["hicom", "head_mod", "senior_mod", "moderator", "trial_mod"]),
  createdAt: zod.string(),
  updatedAt: zod.string().nullish(),
});

/**
 * @summary Delete a staff profile (HICOM+ only)
 */
export const DeleteStaffProfileParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Update a staff member's role (owner only for HICOM; HICOM+ for others)
 */
export const UpdateStaffRoleParams = zod.object({
  userId: zod.coerce.string(),
});

export const UpdateStaffRoleBody = zod.object({
  role: zod.enum(["hicom", "head_mod", "senior_mod", "moderator", "trial_mod"]),
});

export const UpdateStaffRoleResponse = zod.object({
  id: zod.number(),
  discordId: zod.string(),
  username: zod.string(),
  avatar: zod.string().nullish(),
  timezone: zod.string().nullish(),
  about: zod.string().nullish(),
  role: zod.enum(["hicom", "head_mod", "senior_mod", "moderator", "trial_mod"]),
  createdAt: zod.string(),
  updatedAt: zod.string().nullish(),
});

/**
 * @summary List all uploaded files
 */
export const ListFilesResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  originalName: zod.string().optional(),
  mimeType: zod.string(),
  size: zod.number(),
  uploadedBy: zod.string(),
  description: zod.string().nullish(),
  createdAt: zod.string(),
});
export const ListFilesResponse = zod.array(ListFilesResponseItem);

/**
 * @summary Get file metadata
 */
export const GetFileParams = zod.object({
  id: zod.coerce.number(),
});

export const GetFileResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  originalName: zod.string().optional(),
  mimeType: zod.string(),
  size: zod.number(),
  uploadedBy: zod.string(),
  description: zod.string().nullish(),
  createdAt: zod.string(),
});

/**
 * @summary Delete a file (HICOM+ only)
 */
export const DeleteFileParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Download/open a file
 */
export const DownloadFileParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List all AI context entries (owner only)
 */
export const ListBotContextResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  content: zod.string(),
  createdAt: zod.string(),
  updatedAt: zod.string().nullish(),
});
export const ListBotContextResponse = zod.array(ListBotContextResponseItem);

/**
 * @summary Create a new AI context entry (owner only)
 */
export const CreateBotContextBody = zod.object({
  title: zod.string(),
  content: zod.string(),
});

/**
 * @summary Update an AI context entry (owner only)
 */
export const UpdateBotContextParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateBotContextBody = zod.object({
  title: zod.string(),
  content: zod.string(),
});

export const UpdateBotContextResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  content: zod.string(),
  createdAt: zod.string(),
  updatedAt: zod.string().nullish(),
});

/**
 * @summary Delete an AI context entry (owner only)
 */
export const DeleteBotContextParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Send a message to the AI chatbot
 */
export const SendChatMessageBody = zod.object({
  message: zod.string(),
});

export const SendChatMessageResponse = zod.object({
  reply: zod.string(),
  messageId: zod.number(),
});

/**
 * @summary Get recent chat history for the current user
 */
export const GetChatHistoryResponseItem = zod.object({
  id: zod.number(),
  role: zod.enum(["user", "assistant"]),
  content: zod.string(),
  createdAt: zod.string(),
});
export const GetChatHistoryResponse = zod.array(GetChatHistoryResponseItem);
