/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * RCL Staff Portal API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface SuccessResponse {
  success: boolean;
}

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const UserRole = {
  owner: "owner",
  hicom: "hicom",
  head_mod: "head_mod",
  senior_mod: "senior_mod",
  moderator: "moderator",
  trial_mod: "trial_mod",
  pending: "pending",
  none: "none",
} as const;

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus];

export const UserStatus = {
  approved: "approved",
  pending: "pending",
  declined: "declined",
  blacklisted: "blacklisted",
  none: "none",
} as const;

export interface User {
  discordId: string;
  username: string;
  /** @nullable */
  discriminator?: string | null;
  /** @nullable */
  avatar: string | null;
  role: UserRole;
  status: UserStatus;
  /** @nullable */
  blacklistedUntil?: string | null;
}

export type ApplicationStatus =
  (typeof ApplicationStatus)[keyof typeof ApplicationStatus];

export const ApplicationStatus = {
  pending: "pending",
  approved: "approved",
  declined: "declined",
  blacklisted: "blacklisted",
} as const;

export interface Application {
  id: number;
  discordId: string;
  username: string;
  /** @nullable */
  discriminator?: string | null;
  /** @nullable */
  avatar: string | null;
  status: ApplicationStatus;
  /** @nullable */
  role?: string | null;
  /** @nullable */
  blacklistedUntil?: string | null;
  /** @nullable */
  reviewedBy?: string | null;
  createdAt: string;
  /** @nullable */
  updatedAt?: string | null;
}

export type ApprovalInputRole =
  (typeof ApprovalInputRole)[keyof typeof ApprovalInputRole];

export const ApprovalInputRole = {
  trial_mod: "trial_mod",
  moderator: "moderator",
  senior_mod: "senior_mod",
  head_mod: "head_mod",
  hicom: "hicom",
} as const;

export interface ApprovalInput {
  role: ApprovalInputRole;
}

export interface ApplicationStats {
  total: number;
  pending: number;
  approved: number;
  declined: number;
  blacklisted: number;
}

export type StaffProfileRole =
  (typeof StaffProfileRole)[keyof typeof StaffProfileRole];

export const StaffProfileRole = {
  hicom: "hicom",
  head_mod: "head_mod",
  senior_mod: "senior_mod",
  moderator: "moderator",
  trial_mod: "trial_mod",
} as const;

export interface StaffProfile {
  id: number;
  discordId: string;
  username: string;
  /** @nullable */
  avatar?: string | null;
  /** @nullable */
  timezone?: string | null;
  /** @nullable */
  about?: string | null;
  role: StaffProfileRole;
  createdAt: string;
  /** @nullable */
  updatedAt?: string | null;
}

export type StaffProfileInputRole =
  (typeof StaffProfileInputRole)[keyof typeof StaffProfileInputRole];

export const StaffProfileInputRole = {
  hicom: "hicom",
  head_mod: "head_mod",
  senior_mod: "senior_mod",
  moderator: "moderator",
  trial_mod: "trial_mod",
} as const;

export interface StaffProfileInput {
  discordId: string;
  username: string;
  /** @nullable */
  avatar?: string | null;
  /** @nullable */
  timezone?: string | null;
  /** @nullable */
  about?: string | null;
  role: StaffProfileInputRole;
}

export type StaffProfileUpdateRole =
  (typeof StaffProfileUpdateRole)[keyof typeof StaffProfileUpdateRole];

export const StaffProfileUpdateRole = {
  hicom: "hicom",
  head_mod: "head_mod",
  senior_mod: "senior_mod",
  moderator: "moderator",
  trial_mod: "trial_mod",
} as const;

export interface StaffProfileUpdate {
  username?: string;
  /** @nullable */
  avatar?: string | null;
  /** @nullable */
  timezone?: string | null;
  /** @nullable */
  about?: string | null;
  role?: StaffProfileUpdateRole;
}

export type RoleUpdateRole =
  (typeof RoleUpdateRole)[keyof typeof RoleUpdateRole];

export const RoleUpdateRole = {
  hicom: "hicom",
  head_mod: "head_mod",
  senior_mod: "senior_mod",
  moderator: "moderator",
  trial_mod: "trial_mod",
} as const;

export interface RoleUpdate {
  role: RoleUpdateRole;
}

export interface FileRecord {
  id: number;
  name: string;
  originalName?: string;
  mimeType: string;
  size: number;
  uploadedBy: string;
  /** @nullable */
  description?: string | null;
  createdAt: string;
}

export interface ChatMessageInput {
  message: string;
}

export interface ChatResponse {
  reply: string;
  messageId: number;
}

export interface BotContextEntry {
  id: number;
  title: string;
  content: string;
  createdAt: string;
  /** @nullable */
  updatedAt?: string | null;
}

export interface BotContextInput {
  title: string;
  content: string;
}

export type ChatMessageRole =
  (typeof ChatMessageRole)[keyof typeof ChatMessageRole];

export const ChatMessageRole = {
  user: "user",
  assistant: "assistant",
} as const;

export interface ChatMessage {
  id: number;
  role: ChatMessageRole;
  content: string;
  createdAt: string;
}
